version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: habit-tracker-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: habit_tracker
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_TEST_DB: habit_tracker_test
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: